import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
//Initialize aws cognito

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          {" "}
          <Providers>
            <main className="dark text-foreground bg-background min-h-screen">
              {children}
            </main>
            </Providers>
        
      </body>
    </html>
  );
}
