import "server-only";
import { getCityDetailsFromCache } from "./CityDetails";

const cities = [
    "Airdrie",
    "Grande Prairie",
    "Red Deer",
    "Beaumont",
    "Hanna",
    "St. Albert",
    "Bonnyville",
    "Hinton",
    "Spruce Grove",
    "Brazeau",
    "Irricana",
    "Strathcona County",
    "Breton",
    "Lacombe",
    "Strathmore",
    "Calgary",
    "Leduc",
    "Sylvan Lake",
    "Camrose",
    "Lethbridge",
    "Swan Hills",
    "Canmore",
    "McLennan",
    "Taber",
    "Didzbury",
    "Medicine Hat",
    "Turner Valley",
    "Drayton Valley",
    "Olds",
    "Vermillion",
    "Edmonton",
    "Onoway",
    "Wood Buffalo",
    "Ft. Saskatchewan",
    "Provost",
    "Burnaby",
    "Lumby",
    "City of Port Moody",
    "Cache Creek",
    "Maple Ridge",
    "Prince George",
    "Castlegar",
    "Merritt",
    "Prince Rupert",
    "Chemainus",
    "Mission",
    "Richmond",
    "Chilliwack",
    "Nanaimo",
    "Saanich",
    "Clearwater",
    "Nelson",
    "Sooke",
    "Colwood",
    "New Westminster",
    "Sparwood",
    "Coquitlam",
    "North Cowichan",
    "Surrey",
    "Cranbrook",
    "North Vancouver",
    "Terrace",
    "Dawson Creek",
    "Tumbler",
    "Delta",
    "Osoyoos",
    "Vancouver",
    "Fernie",
    "Parksville",
    "Invermere",
    "Peace River",
    "Vernon",
    "Kamloops",
    "Penticton",
    "Victoria",
    "Kaslo",
    "Port Alberni",
    "Whistler",
    "Langley",
    "Port Hardy",
    "Birtle",
    "Flin Flon",
    "Swan River",
    "Brandon",
    "Snow Lake",
    "The Pas",
    "Cranberry Portage",
    "Steinbach",
    "Thompson",
    "Dauphin",
    "Stonewall",
    "Winnipeg",
    "Cap-Pele",
    "Miramichi",
    "Saint John",
    "Fredericton",
    "Moncton",
    "Saint Stephen",
    "Grand Bay-Westfield",
    "Oromocto",
    "Shippagan",
    "Grand Falls",
    "Port Elgin",
    "Sussex",
    "Memramcook",
    "Sackville",
    "Tracadie-Sheila",
    "Argentia",
    "Corner Brook",
    "Paradise",
    "Bishop's Falls",
    "Labrador City",
    "Portaux Basques",
    "Botwood",
    "Mount Pearl",
    "St. John's",
    "Brigus",
    "Town of Hay River",
    "Town of Inuvik",
    "Yellowknife",
    "Amherst",
    "Hants County",
    "Pictou",
    "Annapolis",
    "Inverness County",
    "Pictou County",
    "Argyle",
    "Kentville",
    "Queens",
    "Baddeck",
    "County of Kings",
    "Richmond",
    "Bridgewater",
    "Lunenburg",
    "Shelburne",
    "Cape Breton",
    "Lunenburg County",
    "Stellarton",
    "Chester",
    "Mahone Bay",
    "Truro",
    "Cumberland County",
    "New Glasgow",
    "Windsor",
    "East Hants",
    "New Minas",
    "Yarmouth",
    "Halifax",
    "Parrsboro",
    "Ajax",
    "Halton",
    "Peterborough",
    "Atikokan",
    "Halton Hills",
    "Pickering",
    "Barrie",
    "Hamilton",
    "Port Bruce",
    "Belleville",
    "Hamilton-Wentworth",
    "Port Burwell",
    "Blandford-Blenheim",
    "Hearst",
    "Port Colborne",
    "Blind River",
    "Huntsville",
    "Port Hope",
    "Brampton",
    "Ingersoll",
    "Prince Edward",
    "Brant",
    "James",
    "Quinte West",
    "Brantford",
    "Kanata",
    "Renfrew",
    "Brock",
    "Kincardine",
    "Richmond Hill",
    "Brockville",
    "King",
    "Sarnia",
    "Burlington",
    "Kingston",
    "Sault Ste. Marie",
    "Caledon",
    "Kirkland Lake",
    "Scarborough",
    "Cambridge",
    "Kitchener",
    "Scugog",
    "Chatham-Kent",
    "Larder Lake",
    "Souix Lookout CoC Sioux Lookout",
    "Chesterville",
    "Leamington",
    "Smiths Falls",
    "Clarington",
    "Lennox-Addington",
    "South-West Oxford",
    "Cobourg",
    "Lincoln",
    "St. Catharines",
    "Cochrane",
    "Lindsay",
    "St. Thomas",
    "Collingwood",
    "London",
    "Stoney Creek",
    "Cornwall",
    "Loyalist Township",
    "Stratford",
    "Cumberland",
    "Markham",
    "Sudbury",
    "Deep River",
    "Metro Toronto",
    "Temagami",
    "Dundas",
    "Merrickville",
    "Thorold",
    "Durham",
    "Milton",
    "Thunder Bay",
    "Dymond",
    "Nepean",
    "Tillsonburg",
    "Ear Falls",
    "Newmarket",
    "Timmins",
    "East Gwillimbury",
    "Niagara",
    "Toronto",
    "East Zorra-Tavistock",
    "Niagara Falls",
    "Uxbridge",
    "Elgin",
    "Niagara-on-the-Lake",
    "Vaughan",
    "Elliot Lake",
    "North Bay",
    "Wainfleet",
    "Flamborough",
    "North Dorchester",
    "Wasaga Beach",
    "Fort Erie",
    "North Dumfries",
    "Waterloo",
    "Fort Frances",
    "North York",
    "Gananoque",
    "Norwich",
    "Welland",
    "Georgina",
    "Oakville",
    "Wellesley",
    "Glanbrook",
    "Orangeville",
    "West Carleton",
    "Gloucester",
    "Orillia",
    "West Lincoln",
    "Goulbourn",
    "Osgoode",
    "Whitby",
    "Gravenhurst",
    "Oshawa",
    "Wilmot",
    "Grimsby",
    "Ottawa",
    "Windsor",
    "Guelph",
    "Ottawa-Carleton",
    "Woolwich",
    "Haldimand-Norfork",
    "Owen Sound",
    "York",
    "Alberton",
    "Montague",
    "Stratford",
    "Charlottetown",
    "Souris",
    "Summerside",
    "Cornwall",
    "Alma",
    "Fleurimont",
    "Longueuil",
    "Amos",
    "Gaspe",
    "Marieville",
    "Anjou",
    "Gatineau",
    "Mount Royal",
    "Aylmer",
    "Hull",
    "Montreal",
    "Beauport",
    "Joliette",
    "Montreal Region",
    "Bromptonville",
    "Jonquiere",
    "Montreal-Est",
    "Brosssard",
    "Lachine",
    "Quebec",
    "Chateauguay",
    "Lasalle",
    "Saint-Leonard",
    "Chicoutimi",
    "Laurentides",
    "Sherbrooke",
    "Coaticook",
    "LaSalle",
    "Sorel",
    "Laval",
    "Thetford Mines",
    "Dorval",
    "Lennoxville",
    "Victoriaville",
    "Drummondville",
    "Levis",
    "Avonlea",
    "Melfort",
    "Swift Current",
    "Colonsay",
    "Nipawin",
    "Tisdale",
    "Craik",
    "Prince Albert",
    "Unity",
    "Creighton",
    "Regina",
    "Weyburn",
    "Eastend",
    "Saskatoon",
    "Wynyard",
    "Esterhazy",
    "Shell Lake",
    "Yorkton",
    "Gravelbourg",
    "Carcross",
    "Whitehorse",
  ];
  

export async function getMapPoints() {
 
  const detailsList = await Promise.all(
    cities.map(async (cityName, i) => {
      const city = cityName;
      const province = null; 

      const d = await getCityDetailsFromCache(city);

      if (!d) {
        console.log(`[${i}] skipped: not in cache/DB`, city);
        return null;
      }

      const details = d;

      const lat = details.coords?.lat ?? details.latitude ?? null;
      const lng = details.coords?.lng ?? details.longitude ?? null;

      if (lat == null || lng == null) {
        console.log(
          `[${i}] skipped: missing coords in DB for`,
          details.city ?? city,
          details.province ?? province
        );
        return null;
      }

      return {
        city: details.city ?? city,
        province: details.province ?? province,
        lat: Number(lat),
        lng: Number(lng),
        population: details.demographics?.population ?? null,
        costOfLiving: {
          singleMonthly: details.costOfLiving?.singleMonthly ?? null,
           familyMonthly: details.costOfLiving?.familyMonthly ?? null,
          currency: details.costOfLiving?.currency ?? "CAD",
        },
        jobs: {
          topIndustries: Array.isArray(details.jobOpportunities?.topIndustries)
            ? details.jobOpportunities.topIndustries.slice(0, 5)
            : [],
          growingSectors: Array.isArray(details.jobOpportunities?.growingSectors)
            ? details.jobOpportunities.growingSectors.slice(0, 5)
            : [],
          demandByField: details.jobOpportunities?.demandByField ?? {},
        },
      };
    })
  );

  let points = (detailsList || []).filter(Boolean);

 //demo points if absolutely nothing found
  if (points.length === 0) {
    console.log("⚙️ Using mock demo points...");
    points = [
      {
        city: "Toronto",
        province: "ON",
        lat: 43.6532,
        lng: -79.3832,
        population: 2930000,
        costOfLiving: {
          singleMonthly: 2500,
          familyMonthly: 5200,
          currency: "CAD",
        },
        jobs: {
          topIndustries: ["Tech", "Finance", "Education"],
          growingSectors: ["AI", "Startups"],
          demandByField: { tech: 8.7 },
        },
      },
      {
        city: "Vancouver",
        province: "BC",
        lat: 49.2827,
        lng: -123.1207,
        population: 675000,
        costOfLiving: {
          singleMonthly: 2700,
          familyMonthly: 5400,
          currency: "CAD",
        },
        jobs: {
          topIndustries: ["Film", "Tech", "Tourism"],
          growingSectors: ["Green Energy"],
          demandByField: { film: 7.1 },
        },
      },
      {
        city: "Montreal",
        province: "QC",
        lat: 45.5017,
        lng: -73.5673,
        population: 1780000,
        costOfLiving: {
          singleMonthly: 1900,
          familyMonthly: 4100,
          currency: "CAD",
        },
        jobs: {
          topIndustries: ["Design", "Healthcare"],
          growingSectors: ["AI", "Biotech"],
          demandByField: { design: 6.5 },
        },
      },
    ];
  }

  return points;
}